spring:
  application:
    name: discovery-service

  graphql:
    schema:
      locations: classpath:graphql/
    graphiql:
      enabled: true

dgs:
  graphql:
    schema-locations: classpath:graphql/**

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
