name: Deploy entitlement-service

on:
  push:
    branches: [main]
    paths:
      - "services/entitlement-service/**"
      - "schema/entitlement/**"
      - "specs/events/**"

jobs:
  deploy:
    uses: ./.github/workflows/_deploy-service.yml
    with:
      service: entitlement-service
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_OIDC_ROLE_ARN: ${{ secrets.AWS_OIDC_ROLE_ARN }}
