name: Deploy member-service

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "services/member-service/**"
      - "schema/member/**"

jobs:
  deploy:
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/_deploy-service.yml
    with:
      service: member-service
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_OIDC_ROLE_ARN: ${{ secrets.AWS_OIDC_ROLE_ARN }}
